apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: octalcomputer/gitops01:faee64ded584ffb65de358756f32dc406bf7dec2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
